timetools_tester:timetools_tester.c ../OBLib/String/String.c ../OBLib/String/String.h ../OBLib/Time/TimeTools.c ../OBLib/Time/TimeTools.h
	gcc -iquote ../OBLib/Time -iquote ../OBLib/String  timetools_tester.c ../OBLib/String/String.c ../OBLib/Time/TimeTools.c -o timetools_tester -lm
