stat_tester:stat_tester.c ../../OBLib/String/String.c ../../OBLib/Collection/LinkedList.c ../../OBLib/Util/Stat.c
	gcc -iquote ../../OBLib/Collection -iquote ../../OBLib/Util -iquote ../../OBLib/String stat_tester.c ../../OBLib/String/String.c ../../OBLib/Collection/LinkedList.c ../../OBLib/Util/Stat.c -o stat_tester -lm
